//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioHimicHospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalysisReport
    {
        public int IdAnalysisReport { get; set; }
        public int IdBiomaterialResearch { get; set; }
        public string BloodGlucoseLevel { get; set; }
        public string CholesterolLevels { get; set; }
        public string ThePresenceOfProteinsInTheUrine { get; set; }
        public byte[] Electrocardiography { get; set; }
        public byte[] UltrasoundExamination { get; set; }
        public byte[] ComputedTomography { get; set; }
    
        public virtual BiomaterialResearch BiomaterialResearch { get; set; }
    }
}
