//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioHimicHospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiomaterialResearch
    {
        public int IdBiomaterialResearch { get; set; }
        public int IdPatient { get; set; }
        public int IdLaboraotryService { get; set; }
        public int Cost { get; set; }
    
        public virtual LaboratoryServices LaboratoryServices { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
