//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioHimicHospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiomaterialResearch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BiomaterialResearch()
        {
            this.AnalysisReport = new HashSet<AnalysisReport>();
        }
    
        public int IdBiomaterialResearch { get; set; }
        public int IdPatient { get; set; }
        public int IdLaboraotryService { get; set; }
        public string Price { get; set; }
    
        public virtual LaboratoryServices LaboratoryServices { get; set; }
        public virtual Patients Patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnalysisReport> AnalysisReport { get; set; }
    }
}
