//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioHimicHospital.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public int IdPatient { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime DateOfBirthday { get; set; }
        public string SeriesAndNumberPassport { get; set; }
        public string NumberPhone { get; set; }
        public string Email { get; set; }
        public string PolicyNumber { get; set; }
        public int IdInsuranceCompany { get; set; }
        public Nullable<int> IdOrder { get; set; }
        public string Login { get; set; }
    
        public virtual InsuranceCompany InsuranceCompany { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Users Users { get; set; }
    }
}
